// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCko0TwPZw-MTGuwGjBCSgk3JzdrVxizWs',
    appId: '1:624890762229:web:48ce4073ee22e1010906bc',
    messagingSenderId: '624890762229',
    projectId: 'crimson-41a89',
    authDomain: 'crimson-41a89.firebaseapp.com',
    storageBucket: 'crimson-41a89.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJWrl9RbZ8xHoTglY7jLTkpKS1njjnGfA',
    appId: '1:624890762229:android:0087c12f1c9ee5d40906bc',
    messagingSenderId: '624890762229',
    projectId: 'crimson-41a89',
    storageBucket: 'crimson-41a89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMs0L95LQSpMDw1ueM-_ggIdhBrzRrqVc',
    appId: '1:624890762229:ios:33a043c498c1b8a70906bc',
    messagingSenderId: '624890762229',
    projectId: 'crimson-41a89',
    storageBucket: 'crimson-41a89.appspot.com',
    iosBundleId: 'com.example.crimson',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMs0L95LQSpMDw1ueM-_ggIdhBrzRrqVc',
    appId: '1:624890762229:ios:33a043c498c1b8a70906bc',
    messagingSenderId: '624890762229',
    projectId: 'crimson-41a89',
    storageBucket: 'crimson-41a89.appspot.com',
    iosBundleId: 'com.example.crimson',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCko0TwPZw-MTGuwGjBCSgk3JzdrVxizWs',
    appId: '1:624890762229:web:2c85e6e417e84ecf0906bc',
    messagingSenderId: '624890762229',
    projectId: 'crimson-41a89',
    authDomain: 'crimson-41a89.firebaseapp.com',
    storageBucket: 'crimson-41a89.appspot.com',
  );
}
